# Generated by Django 2.0.2 on 2019-07-25 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('1', 'Men'), ('2', 'Women'), ('3', 'Others')], default='3', max_length=15)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('patient_contact', models.CharField(blank=True, max_length=16, null=True)),
                ('disease_type', models.CharField(choices=[('pf', 'Plasmodium Falciparum'), ('pv', 'Plasmodium Vivax'), ('pm', 'Plasmodium Malaria'), ('po', 'Plasmodium Ovale')], default='pf', max_length=15)),
                ('case_report_type', models.CharField(choices=[('pcd', 'Passive Case Detection'), ('acd', 'Active Case Detection')], default='pcd', max_length=15)),
                ('classification_case', models.CharField(choices=[('imp', 'Imported Case'), ('ind', 'Indigenous Case')], default='imp', max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=15)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_information',
            },
        ),
    ]
