# Generated by Django 2.0.2 on 2019-07-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinformation',
            name='disease_type',
            field=models.CharField(choices=[('pf', 'Plasmodium Falciparum'), ('pv', 'Plasmodium Vivax'), ('pm', 'Plasmodium Malariae'), ('po', 'Plasmodium Ovale')], default='pf', max_length=15),
        ),
    ]
