# Generated by Django 2.0.2 on 2019-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20190725_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinformation',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
