# Generated by Django 2.0.2 on 2019-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20190804_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinformation',
            name='classification_case',
            field=models.CharField(blank=True, choices=[('imp', 'Imported Case'), ('ind', 'Indigenous Case')], max_length=15),
        ),
    ]
