# Generated by Django 2.0.2 on 2019-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20190817_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Pria'), ('2', 'Wanita')], max_length=15),
        ),
    ]
