# Generated by Django 2.0.2 on 2019-09-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20190912_1317'),
        ('sms', '0006_auto_20190820_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinformation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_info', to='masterdata.City'),
        ),
        migrations.AddField(
            model_name='caseinformation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_info', to='masterdata.District'),
        ),
        migrations.AddField(
            model_name='caseinformation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_info', to='masterdata.Province'),
        ),
        migrations.AddField(
            model_name='caseinformation',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_district_info', to='masterdata.SubDistrict'),
        ),
    ]
