# Generated by Django 2.0.2 on 2019-07-25 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=15)),
                ('facility_level', models.CharField(choices=[('3', 'District Health'), ('2', 'Health Center'), ('1', 'Clinic/Health Center Satelite')], default='1', max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=15)),
                ('linked_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthfacility.HealthFacility')),
            ],
            options={
                'db_table': 'health_facility',
            },
        ),
    ]
