# Generated by Django 2.0.2 on 2019-09-16 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20190912_1317'),
        ('healthfacility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_facility', to='masterdata.City'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_facility', to='masterdata.District'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_facility', to='masterdata.Province'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_district_facility', to='masterdata.SubDistrict'),
        ),
    ]
